version: '3'

services:
  # 后端服务
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/huishang-tale
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  # MongoDB 数据库
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
